### ISSUE TITLE
Nested Model update using REST

### ISSUE THREAD

**Issue by zaheershaik** [dtoubelis/sails-cassandra#23]
Hello,

I've encountered some issues while trying to update a model with nested entities using REST. It works fine when the model doesn't have nested entities. Could you please review the following details and let me know if I'm doing something wrong here?

http://localhost:1337/product/d170b9f5-fac3-11e4-80f2-e93099b668ba

**HTTP Put Request - Update nested entity field**
```javascript
{
    "inventory": {
        "id": "d16fa884-fac3-11e4-a761-aac656ffae25",
        "availableQty": 4
    }
}
```

**HTTP Put Request - Update first level field**
```javascript
{
    "description": "updated description"
}
```

**Error Response for both the requests above**
```javascript
{
"error": "E_UNKNOWN",
"status": 500,
"summary": "Encountered an unexpected error",
"raw": {
"query": "SELECT id,price,createdat,updatedat FROM productprice WHERE id = ?;"
}
}
```

**Models**

api/models/Product.js
```javascript
module.exports = {

  attributes: {
    id: {type: 'string', primaryKey: true, autoIncrement: true},
    name: {type: 'string', required: true},
    price: {model: 'productPrice'},
    inventory: {model: 'productInventory'}
  }
};
```

api/models/ProductPrice.js
```javascript
module.exports = {

  attributes: {
    id: {type: 'string', primaryKey: true, autoIncrement: true},
    price: {type: 'float', required: true, defaultsTo: 0.0, index: true}
  }
};
```

api/models/ProductInventory.js
```javascript
module.exports = {

  attributes: {
    id: {type: 'string', primaryKey: true, autoIncrement: true},
    availableQty: {type: 'integer', required: true, defaultsTo: 0, index: true}
  }
};
```

**Comment by dtoubelis** [comment]
Thanks for the excellent bug report. I will look into it asap.

**Comment by dtoubelis** [comment]
For the first request try to spell `"availableQty"` all lower case `"availableqty"`. I have suspicion that something funny is going on with name conversion. If this works then we found the problem.

For the second case, you do not have `"description"` attribute in your model. I think you meant `"name"`. Could you please re-test and confirm?

**Comment by dtoubelis** [comment]
I think for your firts case you need to do something like this:

**Comment by zaheershaik** [comment]
I get a 404 when I try POST or PUT on '/product/d170b9f5-fac3-11e4-80f2-e93099b668ba/inventory/d16fa884-fac3-11e4-a761-aac656ffae25'.

**Comment by zaheershaik** [comment]
I tried the lower case 'availableqty' and I still get the same error. Also, retested by changing the field name to 'name' and the error repeats.

**Comment by dtoubelis** [comment]
The `sails-cassandra` module is actually a `waterline` module, so I'm not using `sails` for testing it at all. I've added a unit test to the master based on your feedback and test to update `name` passes. The test to update inventory is still work in progress. You can have a look for your reference. I will investigate it little bit further, but at this point it seems that problem you are having is not related to the adapter. BTW, does it work if you use say `sails-memory` or `sails-disk`? If you could test and confirm that would be great.
