### ISSUE TITLE
Error while creating collection object

### ISSUE THREAD

**Issue by zaheershaik** [dtoubelis/sails-cassandra#24]
Hello,

I encountered the following error while trying to create a model object with collection. The product object gets created when I don't specify the category. Could you please review and provide some feedback? If you think the request json object is incorrect, then please a share a sample and I will try again.

**Models**

api/models/Product.js
```javascript
module.exports = {

  attributes: {
    id: {type: 'string', primaryKey: true, autoIncrement: true},
    name: {type: 'string', required: true}
    categories: {collection: 'productXCategory', via: 'product'}
  }
};
```

api/models/Category.js
```javascript
module.exports = {

  attributes: {
    id: {type: 'string', primaryKey: true, autoIncrement: true},
    name: {type: 'string', required: 'true'}
  }
};
```

api/models/ProductXCategory.js
```javascript
module.exports = {

  attributes: {
    id: {type: 'string', primaryKey: true, autoIncrement: true},
    product: {model: 'product', index: true},
    category: {model: 'category', index: true}
  }
};
```

**POST Request** http://localhost:1337/product
```javascript
{
    "name": "test product 2",
    "categories": [
        {"id": "1b019e02-fb4a-11e4-9b99-656faa691ace"}
    ]
}
```
**Note**: 1b019e02-fb4a-11e4-9b99-656faa691ace is an existing category.

**Error Response**
```javascript
{
"error": "E_VALIDATION",
"status": 400,
"summary": "1 attribute is invalid",
"model": "Product",
"invalidAttributes": {
"id": [
{
"rule": "string",
"message": "`undefined` should be a string (instead of \"6\", which is a number)"
}
]
}
}

**Comment by dtoubelis** [comment]
I created a test case to simulate this behavior and it seems that waterline/sails attempts to create new entries in nested collections instead of updating existing ones. This would explain the `E_VALIDATION` error as it is trying to create new record with `"id"` you specified and this is not allowed when `autoIncrement` is in force. I'm still working on it but I have no clue so far how to work around this problem. Feel free to share if your have any ideas.

**Comment by dtoubelis** [comment]
Please try this:

`POST /product/:prodict_id/categories/add/1b019e02-fb4a-11e4-9b99-656faa691ace`

**Comment by zaheershaik** [comment]
Thanks for the feedback. Apologies for posting errors if any which might not be related to your module.

I tried the POST query, but that resulted in same error. 

The workaround I have in place is a custom config route with 'post /product/:id/category' in config/routes.js.

Feel free to close the issue or let me know and I can close it.

**Comment by dtoubelis** [comment]
It is indeed not related to the adapter. but now I have another test case for the module :smile: Thanks for your bug report anyway.
