### ISSUE TITLE
[Feature Request] Adding .query() method for raw cql query

### ISSUE THREAD

**Issue by masumsoft** [dtoubelis/sails-cassandra#26]
It would be great if there was an option for raw cql query similar to other adapters. Something like a .query() method that will allow custom queries to be passed down from Waterline and executed against cassandra cql driver.

**Comment by dtoubelis** [comment]
Yes, this is on the roadmap, I was just waiting when somebody asks :smile: .

**Comment by dtoubelis** [comment]
Support for raw queries is now in npm.
