### ISSUE TITLE
Model query sort by timeuuid field

### ISSUE THREAD

**Issue by victorbadila** [dtoubelis/sails-cassandra#30]
I have a model with the following attribute:
```
id: { 
  type: 'string', 
  autoIncrement: true,
  primaryKey: true
}
```
The `string` id translates into `timeuuid` on cassandra side. However when trying to query the table sorting by id:
```
Entity2
  .find()
  .sort({id: 'desc'})
  .exec(function cb(err, ents) { ... });
```
the entities do not arrive in the normal order, and this can be seen by checking the `createdAt` column, which I have not disabled from the model.

I know that in cql in order to make comparisons between `timeuuid` fields one could use 'dateof' function, which extracts the `timestamp` from a `timeuuid`. Any idea if I am doing something wrong in my query or if the functionality I am trying to achieve is / will be supported in sails-cassandra?

**Comment by dtoubelis** [comment]
`sort()` is not supported by sails-cassandra as indicated [here](https://github.com/dtoubelis/sails-cassandra#456-limit-sort-skip) and it is likely will never be supported. Cassandra is NOT RELATIONAL DATABASE and records can only be sorted in CLUSTERING ORDER which is defined by underlying data model (also see [here](http://stackoverflow.com/questions/21948901/cassandra-cql-select-sorting)). So having sorts like in relational database is not possible.
