### ISSUE TITLE
The Array of queries to batch execute can not be empty

### ISSUE THREAD

**Issue by jimmyjamieson** [dtoubelis/sails-cassandra#31]
I'm giving this adapter a shot and I'm attempting to add a new record via query strings (I've set-up my controller to do this and it works fine for sails-disk). I add a new record and I get the error:

"The Array of queries to batch execute can not be empty"

Do you know what would be causing this?

I can paste you the full log output if needed.

**Comment by dtoubelis** [comment]
Could you paste the code sample that causing the error? From your description it is not clear what method you are using. Is it just `.query()` or something else?

**Comment by jimmyjamieson** [comment]
Gimme a bit to get back to you. I removed my cassandra (windows) install to revert back to 2.1 and it's not installing correctly. I'll probably set one up on digital ocean or similar.

**Comment by dtoubelis** [comment]
Are you still having this issue or shall I close the ticket?
