### ISSUE TITLE
Does not automatically create keyspace and columnfamily for use with sails

### ISSUE THREAD

**Issue by Utkarsh85** [dtoubelis/sails-cassandra#32]
I am new to using cassandra with sails. I have created the application which works fine with sails-disk but when switching to sails-cassandra, I am receiving errors that keyspace, columnfamily does not exist. Do I have to manually create them using  cqlsh.

**Comment by dtoubelis** [comment]
The connector should create tables automatically. However, cassandra is not relational database, so make sure you understand big table concept and when to create indexes. Also have a look at test cases in tests directory. They executed automatically on every build and they create a new database every time.

**Comment by Utkarsh85** [comment]
Thanks for the quick response. I will try to work on it and get back to you.

**Comment by dtoubelis** [comment]
You need to create keyspace manually and columnfamilies/tables will be created by adapter. However, I always recommend creating tables manually as well, since waterline only supports subset of datatypes available in Cassandra and it is suboptimal.
