### ISSUE TITLE
readme.md doesnt mention `findOne`

### ISSUE THREAD

**Issue by BransonGitomeh** [dtoubelis/sails-cassandra#35]
i run into a little error with findOne() in my code and i looked at the read me and i almost panicked that it wasn't supported, till i fixed the code, that can be very misleading, but everything works, very helpfull project

**Comment by dtoubelis** [comment]
Waterline interfaces only specify minimal set of methods that are required to be implemented by an adapter. `findOne()` is optional and it is simulated by Waterline internally (it is essentially `find()` with `limit()`) if native implementation is not available. So, there is nothing to worry about as long as you follow Waterline API usage guidelines :-) The readme only outlines behaviors that are different in any way from the norm.

**Comment by BransonGitomeh** [comment]
aweosome, thanks so much, i was migrating a project to cassandra and so far everything works fine, another issue i run into is maybe `populate()` do populates work?

**Comment by dtoubelis** [comment]
As far as I know it should work. The thing to keep in mind though that Cassandra is not a relational database, so some features may work not as expected or not work at all. If you can provide a specific example I may be able to reproduce it in a unit test and then add another note to the readme.
