### ISSUE TITLE
Support of Cassandra versions

### ISSUE THREAD

**Issue by SergeyJyravlev** [dtoubelis/sails-cassandra#41]
Hi!

This library (sails-cassandra) doesn't support the version 3.1 and 3.2 of Cassandra.

Are you going to have the support for these versions?

**Comment by dtoubelis** [comment]
Is there anything special in those modules? I can just bump the version if this is all it takes.

**Comment by dtoubelis** [comment]
Dependencies have been updated. Please use v0.12.11 of the adapter.
