### ISSUE TITLE
sails.js team says thank you!

### ISSUE THREAD

**Issue by tjwebb** [dtoubelis/sails-cassandra#9]
Hey this looks like a great project, I see your PR in waterline-docs. I'm just looking it over right quick before we merge you into the list

**Comment by tjwebb** [comment]
> lessThen

Do you mean lessTh**a**n?

**Comment by tjwebb** [comment]
Typically for consistency, waterline adapters are versioned after the waterline version they are compatible with. e.g. the sails-cassandra 0.10.x series indicates compatibility with the waterline 0.10.x series.

**Comment by dtoubelis** [comment]
Updated version just few minutes ago.

**Comment by dtoubelis** [comment]
The adapter currently implements `semantic`. I'm adding basic support for `migratable` in order to be able to run automated tests.

**Comment by dtoubelis** [comment]
- Fixed _'Then'_ vs  _'Th**a**n'_ issue (Duh!)
- Tests are passing now.
